server:
  port: 8090

spring:
    datasource:
        name: swzl
        url: jdbc:mysql://localhost:3306/swzl
        username: root
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.github.mahui53541.graduation.model


#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

#日志打印（SQL）
logging:
  level:
    com.github.mahui53541.graduation.mapper: DEBUG

#Jwt
jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  tokenHead: Bearer